"""add_book_images_table_revert

Revision ID: 01e65ea8d55b
Revises: e42fb9038c08
Create Date: 2025-10-30 11:54:35.568849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01e65ea8d55b'
down_revision = 'e42fb9038c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_images_image_id'), table_name='book_images')
    op.drop_table('book_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_images',
    sa.Column('image_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('image_order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alt_text', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name=op.f('book_images_ibfk_1')),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_book_images_image_id'), 'book_images', ['image_id'], unique=False)
    # ### end Alembic commands ###