"""add_read_sample_and_audio_sample_to_books

Revision ID: 0200ff33ae8f
Revises: 2115b3e076f3
Create Date: 2025-10-30 11:01:09.925983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0200ff33ae8f'
down_revision = '2115b3e076f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('read_sample', mysql.LONGTEXT(), nullable=True))
    op.add_column('books', sa.Column('audio_sample', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'audio_sample')
    op.drop_column('books', 'read_sample')
    # ### end Alembic commands ###