"""“revert_slug_latest”

Revision ID: 0345921b24ed
Revises: b37db2d80c82
Create Date: 2025-11-23 13:59:04.628885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0345921b24ed'
down_revision = 'b37db2d80c82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_books_slug'), 'books', ['slug'], unique=True)
    op.add_column('stationery', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_stationery_slug'), 'stationery', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stationery_slug'), table_name='stationery')
    op.drop_column('stationery', 'slug')
    op.drop_index(op.f('ix_books_slug'), table_name='books')
    op.drop_column('books', 'slug')
    # ### end Alembic commands ###