"""“update_slide_content_color_advance”

Revision ID: 0470097994ae
Revises: d2cf209c6fff
Create Date: 2025-11-18 21:00:20.449446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0470097994ae'
down_revision = 'd2cf209c6fff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide_contents', sa.Column('selected_item_type', sa.String(length=20), nullable=True))
    op.add_column('slide_contents', sa.Column('selected_item_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slide_contents', 'selected_item_id')
    op.drop_column('slide_contents', 'selected_item_type')
    # ### end Alembic commands ###