"""“update_best_seller”

Revision ID: 0873e8ea32f1
Revises: a7fc5ec9ae46
Create Date: 2025-12-02 09:00:39.242733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0873e8ea32f1'
down_revision = 'a7fc5ec9ae46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_is_active', table_name='notifications')
    op.drop_index('ix_notifications_notification_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('background_color', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('text_color', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notifications_notification_id', 'notifications', ['notification_id'], unique=False)
    op.create_index('ix_notifications_is_active', 'notifications', ['is_active'], unique=False)
    # ### end Alembic commands ###