"""add_ghn_fields_to_orders

Revision ID: 1975420643c2
Revises: a79d2ede4f36
Create Date: 2025-10-28 11:27:03.103207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1975420643c2'
down_revision = 'a79d2ede4f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('expected_delivery_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('package_weight', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_length', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_width', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_height', sa.Integer(), nullable=True))
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'shipping_insurance_value')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'cod_value')
    op.drop_column('orders', 'district_name')
    op.drop_column('orders', 'province_name')
    op.drop_column('orders', 'ward_name')
    op.drop_column('orders', 'shipping_service_type_id')
    op.drop_column('orders', 'shipping_weight')
    op.drop_column('orders', 'actual_delivery_date')
    op.drop_column('orders', 'cod_failed_amount')
    op.drop_column('orders', 'shipping_dimensions')
    op.drop_column('orders', 'shipping_status')
    op.drop_column('orders', 'shipping_coupon_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_coupon_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('orders', sa.Column('shipping_status', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('orders', sa.Column('shipping_dimensions', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('orders', sa.Column('cod_failed_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('actual_delivery_date', mysql.DATETIME(), nullable=True))
    op.add_column('orders', sa.Column('shipping_weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_service_type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ward_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('province_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('district_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('cod_value', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_insurance_value', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_date', mysql.DATETIME(), nullable=True))
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'expected_delivery_time')
    # ### end Alembic commands ###