"""add_notification_formatting_fields

Revision ID: 1990f1791bc5
Revises: 43cf45988470
Create Date: 2025-12-02 09:20:24.284539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1990f1791bc5'
down_revision = '43cf45988470'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('text_align', sa.String(length=10), nullable=True))
    op.add_column('notifications', sa.Column('font_weight', sa.String(length=10), nullable=True))
    op.add_column('notifications', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'message',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.drop_column('notifications', 'image_url')
    op.drop_column('notifications', 'font_weight')
    op.drop_column('notifications', 'text_align')
    # ### end Alembic commands ###