"""“update_ghn_revert-version”

Revision ID: 20b3e3fc4e15
Revises: 7b68feebf56a
Create Date: 2025-10-28 13:35:49.799969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b3e3fc4e15'
down_revision = '7b68feebf56a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###