"""add_remaining_ghn_fields

Revision ID: 40780d8345d3
Revises: 1975420643c2
Create Date: 2025-10-28 11:27:21.662746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40780d8345d3'
down_revision = '1975420643c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###