"""add_notifications_table

Revision ID: 43cf45988470
Revises: 0873e8ea32f1
Create Date: 2025-12-02 09:09:39.015998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cf45988470'
down_revision = '0873e8ea32f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###