"""create_book_images_table

Revision ID: 4b3fa1da9622
Revises: 5325a36f291b
Create Date: 2025-10-30 11:38:25.505418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3fa1da9622'
down_revision = '5325a36f291b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###