"""“update_stationery_GHN_update_1”

Revision ID: 52bfa0353b27
Revises: 997591e127bd
Create Date: 2025-11-22 09:34:09.083645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bfa0353b27'
down_revision = '997591e127bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###