"""add_image2_url_and_image3_url_to_books

Revision ID: 5325a36f291b
Revises: 0200ff33ae8f
Create Date: 2025-10-30 11:25:48.006835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5325a36f291b'
down_revision = '0200ff33ae8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image2_url', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('image3_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'image3_url')
    op.drop_column('books', 'image2_url')
    # ### end Alembic commands ###