"""“update_stationery_GHN”

Revision ID: 55c4548a7a36
Revises: 0470097994ae
Create Date: 2025-11-22 09:07:37.991914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55c4548a7a36'
down_revision = '0470097994ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('stationery_id', sa.Integer(), nullable=True))
    op.alter_column('order_items', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'order_items', 'stationery', ['stationery_id'], ['stationery_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'stationery_id')
    # ### end Alembic commands ###