"""“update_ghn_revert_4”

Revision ID: 5a78428d9437
Revises: f89a227ad8c9
Create Date: 2025-10-28 16:53:23.216731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a78428d9437'
down_revision = 'f89a227ad8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_ghn_order_code'), table_name='orders')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'ghn_province_id')
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'ghn_district_id')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'ghn_ward_code')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'ghn_province_name')
    op.drop_column('orders', 'ghn_order_code')
    op.drop_column('orders', 'ghn_ward_name')
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'ghn_district_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ghn_district_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('package_weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_length', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_order_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('orders', sa.Column('ghn_province_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_fee', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_code', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_district_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_height', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_province_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_width', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_orders_ghn_order_code'), 'orders', ['ghn_order_code'], unique=False)
    # ### end Alembic commands ###