"""“update_description”

Revision ID: 6b2484bab295
Revises: d7c3d7d8a3f1
Create Date: 2025-10-27 11:28:10.892238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b2484bab295'
down_revision = 'd7c3d7d8a3f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('brief_description', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('full_description', mysql.LONGTEXT(), nullable=True))
    op.drop_column('books', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_column('books', 'full_description')
    op.drop_column('books', 'brief_description')
    # ### end Alembic commands ###