"""add_email_verification_token_field

Revision ID: 6e88cca92d6b
Revises: 9d07d8418dbf
Create Date: 2025-10-16 11:12:41.240901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e88cca92d6b'
down_revision = '9d07d8418dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token')
    # ### end Alembic commands ###