"""Add phone_number to users and addresses table

Revision ID: 6fb1245c571f
Revises: 5b61b952d49d
Create Date: 2025-10-15 20:40:20.269798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fb1245c571f'
down_revision = '5b61b952d49d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone_number', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_line1', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_line2', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address_line2')
    op.drop_column('orders', 'shipping_address_line1')
    op.drop_column('orders', 'shipping_phone_number')
    op.drop_column('orders', 'guest_email')
    # ### end Alembic commands ###