"""“update_ghn_revert-version2”

Revision ID: 79a143245bae
Revises: 20b3e3fc4e15
Create Date: 2025-10-28 13:36:41.442187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79a143245bae'
down_revision = '20b3e3fc4e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'ghn_province_id')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'ward_name')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'expected_delivery_time')
    op.drop_column('orders', 'shipping_service_name')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'ghn_ward_code')
    op.drop_column('orders', 'district_name')
    op.drop_column('orders', 'province_name')
    op.drop_column('orders', 'ghn_order_code')
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'ghn_district_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ghn_district_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_length', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_order_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('orders', sa.Column('province_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('district_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_code', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('orders', sa.Column('package_width', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_service_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('expected_delivery_time', mysql.DATETIME(), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_fee', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('ward_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('package_weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_province_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_height', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###