"""“send_code”

Revision ID: 79b66ee162f3
Revises: 818ba416cc2b
Create Date: 2025-12-01 18:57:40.825125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b66ee162f3'
down_revision = '818ba416cc2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###