"""“update_ghn_elements”

Revision ID: 7b68feebf56a
Revises: b38ceacacdd0
Create Date: 2025-10-28 13:00:22.897320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b68feebf56a'
down_revision = 'b38ceacacdd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###