"""Add font and image size properties to slide_contents

Revision ID: 818ba416cc2b
Revises: ce6c2732c76e
Create Date: 2025-11-28 13:53:30.802871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818ba416cc2b'
down_revision = 'ce6c2732c76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide_contents', sa.Column('title_font_size', sa.String(length=10), nullable=True))
    op.add_column('slide_contents', sa.Column('body_font_size', sa.String(length=10), nullable=True))
    op.add_column('slide_contents', sa.Column('title_font_family', sa.String(length=50), nullable=True))
    op.add_column('slide_contents', sa.Column('body_font_family', sa.String(length=50), nullable=True))
    op.add_column('slide_contents', sa.Column('image_width', sa.String(length=10), nullable=True))
    op.add_column('slide_contents', sa.Column('image_height', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slide_contents', 'image_height')
    op.drop_column('slide_contents', 'image_width')
    op.drop_column('slide_contents', 'body_font_family')
    op.drop_column('slide_contents', 'title_font_family')
    op.drop_column('slide_contents', 'body_font_size')
    op.drop_column('slide_contents', 'title_font_size')
    # ### end Alembic commands ###