"""“update_stationery”

Revision ID: 8b2851f4d6d5
Revises: fd9c15306dd0
Create Date: 2025-11-18 15:55:43.821810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2851f4d6d5'
down_revision = 'fd9c15306dd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###