"""“update_ghn_revert”

Revision ID: 9689d4ad9fab
Revises: d30b8a2e3daa
Create Date: 2025-10-28 14:44:32.758495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9689d4ad9fab'
down_revision = 'd30b8a2e3daa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'ghn_district_name')
    op.drop_column('orders', 'ghn_province_id')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'ghn_district_id')
    op.drop_column('orders', 'ghn_province_name')
    op.drop_column('orders', 'ghn_ward_code')
    op.drop_column('orders', 'ghn_ward_name')
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'package_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('package_weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_height', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_code', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('orders', sa.Column('ghn_province_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_district_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_width', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_province_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_district_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_fee', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('package_length', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###