"""“update_stationery_GHN_revert”

Revision ID: 997591e127bd
Revises: 55c4548a7a36
Create Date: 2025-11-22 09:25:14.332920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '997591e127bd'
down_revision = '55c4548a7a36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('order_items_ibfk_3', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'stationery_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('stationery_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_items_ibfk_3', 'order_items', 'stationery', ['stationery_id'], ['stationery_id'])
    op.alter_column('order_items', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###