"""sync_ghn_fields_with_model

Revision ID: 9a84b98a357c
Revises: 1975420643c2
Create Date: 2025-10-28 11:31:19.519558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a84b98a357c'
down_revision = '1975420643c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###