"""Remove phone_number from users table

Revision ID: 9d07d8418dbf
Revises: df371c5786fe
Create Date: 2025-10-15 20:53:44.051082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d07d8418dbf'
down_revision = 'df371c5786fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###