"""“create_noti”

Revision ID: a7fc5ec9ae46
Revises: 79b66ee162f3
Create Date: 2025-12-02 08:53:32.891930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fc5ec9ae46'
down_revision = '79b66ee162f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###