"""“revert_slug”

Revision ID: b37db2d80c82
Revises: abec6b7e5b9c
Create Date: 2025-11-23 13:43:20.709092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b37db2d80c82'
down_revision = 'abec6b7e5b9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_slug', table_name='books')
    op.drop_column('books', 'slug')
    op.drop_index('ix_stationery_slug', table_name='stationery')
    op.drop_column('stationery', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationery', sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_stationery_slug', 'stationery', ['slug'], unique=False)
    op.add_column('books', sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_books_slug', 'books', ['slug'], unique=False)
    # ### end Alembic commands ###