"""add_ghn_order_code_and_tracking_fields

Revision ID: b38ceacacdd0
Revises: bc604c55551b
Create Date: 2025-10-28 12:23:36.566773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38ceacacdd0'
down_revision = 'bc604c55551b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('province_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('district_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('ward_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'ward_name')
    op.drop_column('orders', 'district_name')
    op.drop_column('orders', 'province_name')
    # ### end Alembic commands ###