"""Add cod_amount to orders table

Revision ID: b6e823fcc94b
Revises: 9aaaf147efb2
Create Date: 2025-10-29 11:21:00.650745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e823fcc94b'
down_revision = '9aaaf147efb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cod_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cod_amount')
    # ### end Alembic commands ###