"""Add shipping_full_name, shipping_method, and payment_method to Order model_revert

Revision ID: bca150d31bbd
Revises: b94a70c2dfeb
Create Date: 2025-10-28 18:39:22.222450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bca150d31bbd'
down_revision = 'b94a70c2dfeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_ghn_order_code'), table_name='orders')
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'ghn_ward_code')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'ghn_order_code')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'shipping_full_name')
    op.drop_column('orders', 'shipping_method')
    op.drop_column('orders', 'ghn_district_name')
    op.drop_column('orders', 'ghn_province_name')
    op.drop_column('orders', 'ghn_province_id')
    op.drop_column('orders', 'ghn_district_id')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'ghn_ward_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ghn_ward_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_fee', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('package_width', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_district_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_province_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_province_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_district_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_method', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_full_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('package_weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ghn_order_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_method', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_code', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_length', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('package_height', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_orders_ghn_order_code'), 'orders', ['ghn_order_code'], unique=False)
    # ### end Alembic commands ###