"""“update_slide_content”

Revision ID: be5af3e5fcad
Revises: 8b2851f4d6d5
Create Date: 2025-11-18 20:42:26.832484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5af3e5fcad'
down_revision = '8b2851f4d6d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###