"""“add_sta_order”

Revision ID: ce6c2732c76e
Revises: d40e51104447
Create Date: 2025-11-26 11:48:44.004071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce6c2732c76e'
down_revision = 'd40e51104447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_stationery_items_order_stationery_item_id', table_name='order_stationery_items')
    op.drop_table('order_stationery_items')
    op.add_column('order_items', sa.Column('stationery_id', sa.Integer(), nullable=True))
    op.alter_column('order_items', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'order_items', 'stationery', ['stationery_id'], ['stationery_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'stationery_id')
    op.create_table('order_stationery_items',
    sa.Column('order_stationery_item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stationery_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_at_purchase', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='order_stationery_items_ibfk_1'),
    sa.ForeignKeyConstraint(['stationery_id'], ['stationery.stationery_id'], name='order_stationery_items_ibfk_2'),
    sa.PrimaryKeyConstraint('order_stationery_item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_order_stationery_items_order_stationery_item_id', 'order_stationery_items', ['order_stationery_item_id'], unique=False)
    # ### end Alembic commands ###