"""“update_slide_content_color”

Revision ID: d2cf209c6fff
Revises: be5af3e5fcad
Create Date: 2025-11-18 20:51:52.070522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cf209c6fff'
down_revision = 'be5af3e5fcad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide_contents', sa.Column('title_color', sa.String(length=20), nullable=True))
    op.add_column('slide_contents', sa.Column('body_color', sa.String(length=20), nullable=True))
    op.add_column('slide_contents', sa.Column('primary_button_bg_color', sa.String(length=20), nullable=True))
    op.add_column('slide_contents', sa.Column('primary_button_text_color', sa.String(length=20), nullable=True))
    op.add_column('slide_contents', sa.Column('secondary_button_bg_color', sa.String(length=20), nullable=True))
    op.add_column('slide_contents', sa.Column('secondary_button_text_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slide_contents', 'secondary_button_text_color')
    op.drop_column('slide_contents', 'secondary_button_bg_color')
    op.drop_column('slide_contents', 'primary_button_text_color')
    op.drop_column('slide_contents', 'primary_button_bg_color')
    op.drop_column('slide_contents', 'body_color')
    op.drop_column('slide_contents', 'title_color')
    # ### end Alembic commands ###