"""Add missing GHN fields to orders table

Revision ID: d30b8a2e3daa
Revises: 79a143245bae
Create Date: 2025-10-28 14:28:19.016166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30b8a2e3daa'
down_revision = '79a143245bae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ghn_province_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('ghn_district_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('ghn_province_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_district_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('package_weight', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_length', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_width', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'ghn_ward_name')
    op.drop_column('orders', 'ghn_district_name')
    op.drop_column('orders', 'ghn_province_name')
    op.drop_column('orders', 'ghn_ward_code')
    op.drop_column('orders', 'ghn_district_id')
    op.drop_column('orders', 'ghn_province_id')
    # ### end Alembic commands ###