"""“update_buttons_slide”

Revision ID: d40e51104447
Revises: 0345921b24ed
Create Date: 2025-11-23 15:30:26.049062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40e51104447'
down_revision = '0345921b24ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide_contents', sa.Column('primary_button_label', sa.String(length=255), nullable=True))
    op.add_column('slide_contents', sa.Column('secondary_button_label', sa.String(length=255), nullable=True))
    op.add_column('slide_contents', sa.Column('primary_button_url', sa.String(length=500), nullable=True))
    op.add_column('slide_contents', sa.Column('secondary_button_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slide_contents', 'secondary_button_url')
    op.drop_column('slide_contents', 'primary_button_url')
    op.drop_column('slide_contents', 'secondary_button_label')
    op.drop_column('slide_contents', 'primary_button_label')
    # ### end Alembic commands ###