"""add_book_position_and_discount_fields

Revision ID: d7c3d7d8a3f1
Revises: eeef3c0361a4
Create Date: 2025-10-23 20:13:31.775406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c3d7d8a3f1'
down_revision = 'eeef3c0361a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_best_seller', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('books', sa.Column('is_new', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('books', sa.Column('is_discount', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('books', sa.Column('is_slide1', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('books', sa.Column('is_slide2', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('books', sa.Column('is_slide3', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('books', sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('books', sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('books', sa.Column('discounted_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'discounted_price')
    op.drop_column('books', 'discount_amount')
    op.drop_column('books', 'discount_percentage')
    op.drop_column('books', 'is_slide3')
    op.drop_column('books', 'is_slide2')
    op.drop_column('books', 'is_slide1')
    op.drop_column('books', 'is_discount')
    op.drop_column('books', 'is_new')
    op.drop_column('books', 'is_best_seller')
    # ### end Alembic commands ###