"""Remove phone_number from users table

Revision ID: df371c5786fe
Revises: 6fb1245c571f
Create Date: 2025-10-15 20:43:13.444447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df371c5786fe'
down_revision = '6fb1245c571f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###