"""Add GHN integration fields to orders table

Revision ID: dfd3b6fcd2af
Revises: 9689d4ad9fab
Create Date: 2025-10-28 16:12:24.093296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd3b6fcd2af'
down_revision = '9689d4ad9fab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ghn_order_code', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_province_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('ghn_district_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('province_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('district_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('ward_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('expected_delivery_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('package_weight', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_length', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_width', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'expected_delivery_time')
    op.drop_column('orders', 'shipping_service_name')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'ward_name')
    op.drop_column('orders', 'district_name')
    op.drop_column('orders', 'province_name')
    op.drop_column('orders', 'ghn_ward_code')
    op.drop_column('orders', 'ghn_district_id')
    op.drop_column('orders', 'ghn_province_id')
    op.drop_column('orders', 'ghn_order_code')
    # ### end Alembic commands ###