"""add_book_images_table

Revision ID: e42fb9038c08
Revises: 4b3fa1da9622
Create Date: 2025-10-30 11:39:34.041372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42fb9038c08'
down_revision = '4b3fa1da9622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###