"""add_is_free_ship_to_books_and_stationery

Revision ID: eee44b00fe37
Revises: 3563ed10d775
Create Date: 2025-12-08 13:02:52.244183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee44b00fe37'
down_revision = '3563ed10d775'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_free_ship', sa.Boolean(), nullable=False))
    op.add_column('stationery', sa.Column('is_free_ship', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stationery', 'is_free_ship')
    op.drop_column('books', 'is_free_ship')
    # ### end Alembic commands ###