"""Add GHN fields to orders table

Revision ID: f89a227ad8c9
Revises: ec99db366c9f
Create Date: 2025-10-28 16:30:07.709733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89a227ad8c9'
down_revision = 'ec99db366c9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ghn_order_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('ghn_province_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('ghn_district_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('ghn_province_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_district_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('ghn_ward_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('package_weight', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_length', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_width', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('package_height', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_ghn_order_code'), 'orders', ['ghn_order_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_ghn_order_code'), table_name='orders')
    op.drop_column('orders', 'package_height')
    op.drop_column('orders', 'package_width')
    op.drop_column('orders', 'package_length')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'shipping_service_id')
    op.drop_column('orders', 'ghn_ward_name')
    op.drop_column('orders', 'ghn_district_name')
    op.drop_column('orders', 'ghn_province_name')
    op.drop_column('orders', 'ghn_ward_code')
    op.drop_column('orders', 'ghn_district_id')
    op.drop_column('orders', 'ghn_province_id')
    op.drop_column('orders', 'ghn_order_code')
    # ### end Alembic commands ###