"""add_mobile_image_url

Revision ID: fc6bce33973a
Revises: set_defaults_002
Create Date: 2025-12-02 09:57:40.560513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc6bce33973a'
down_revision = 'set_defaults_002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use LONGTEXT for mobile_image_url to support base64 images
    op.add_column('notifications', sa.Column('mobile_image_url', mysql.LONGTEXT(), nullable=True))
    # Do NOT revert image_url to Text, keep it as LONGTEXT
    # op.alter_column('notifications', 'image_url', ...)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('notifications', 'image_url', ...)
    op.drop_column('notifications', 'mobile_image_url')
    # ### end Alembic commands ###