"""“update_review”

Revision ID: fd9c15306dd0
Revises: 01e65ea8d55b
Create Date: 2025-11-07 14:33:15.845097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9c15306dd0'
down_revision = '01e65ea8d55b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###