#!/usr/bin/env python3
"""
Phase 4 — copy existing MySQL data into the Supabase Postgres schema.

Preserves integer primary keys (the Supabase schema uses
`generated BY DEFAULT as identity`, so explicit ids insert fine), copies tables
in FK-dependency order, then realigns every identity sequence to max(id).

The dropped `zalo_tokens` table is intentionally skipped (Zalo retired).

Usage:
    pip install sqlalchemy pymysql psycopg2-binary
    export MYSQL_URL='mysql+pymysql://approot:PASS@localhost/bookstore_db'
    # Supabase: Project Settings → Database → Connection string (URI), use the
    # DIRECT connection (port 5432), not the pooler, so sequences/DDL behave.
    export SUPABASE_DB_URL='postgresql://postgres:PASS@db.<ref>.supabase.co:5432/postgres'
    # Optional: skip tables (comma-separated). E.g. don't bring over test orders:
    export SKIP_TABLES='orders,order_items'
    python supabase/scripts/import_from_mysql.py

Notes:
  * Auth: rows land in public.users with auth_id = NULL. Supabase Auth has no
    credentials for them yet. Either (a) have users reset their password, or
    (b) backfill auth.users via the Admin API and the on-signup trigger will
    link by email. Until linked, RLS treats them as not-logged-in.
  * Re-runnable: rows are inserted with ON CONFLICT DO NOTHING semantics.
"""
import os
import sys
from sqlalchemy import create_engine, MetaData, Table, select, text
from sqlalchemy.dialects.postgresql import insert as pg_insert

# FK-safe order. zalo_tokens deliberately omitted.
TABLE_ORDER = [
    "roles", "users", "addresses",
    "authors", "categories", "books", "stationery",
    "book_authors", "book_categories", "stationery_categories",
    "reviews", "stationery_reviews", "wishlists",
    "orders", "order_items",
    "slide_contents", "notifications", "admin_login_codes",
]

# (table, identity column) pairs whose sequence must be realigned after load.
IDENTITY_COLS = {
    "roles": "role_id", "users": "user_id", "addresses": "address_id",
    "authors": "author_id", "categories": "category_id", "books": "book_id",
    "stationery": "stationery_id", "reviews": "review_id",
    "stationery_reviews": "review_id", "orders": "order_id",
    "order_items": "order_item_id", "slide_contents": "slide_content_id",
    "notifications": "notification_id", "admin_login_codes": "id",
}


def main() -> int:
    mysql_url = os.environ.get("MYSQL_URL")
    pg_url = os.environ.get("SUPABASE_DB_URL")
    if not mysql_url or not pg_url:
        print("Set MYSQL_URL and SUPABASE_DB_URL env vars.", file=sys.stderr)
        return 1

    # Tables to skip (e.g. SKIP_TABLES='orders,order_items' to drop test orders).
    skip = {t.strip() for t in os.environ.get("SKIP_TABLES", "").split(",") if t.strip()}
    if skip:
        print(f"Skipping tables: {', '.join(sorted(skip))}")

    src = create_engine(mysql_url)
    dst = create_engine(pg_url)

    src_meta = MetaData()
    dst_meta = MetaData()
    src_meta.reflect(bind=src)
    dst_meta.reflect(bind=dst, schema="public")

    with src.connect() as sconn, dst.begin() as dconn:
        for tname in TABLE_ORDER:
            if tname in skip:
                print(f"· skip {tname} (SKIP_TABLES)")
                continue
            if tname not in src_meta.tables:
                print(f"· skip {tname} (not in source)")
                continue
            src_table = src_meta.tables[tname]
            dst_table = dst_meta.tables.get(f"public.{tname}")
            if dst_table is None:
                print(f"· skip {tname} (not in target)")
                continue

            # Only copy columns present in BOTH schemas.
            common_cols = [c.name for c in dst_table.columns if c.name in src_table.columns]
            rows = sconn.execute(select(*[src_table.c[c] for c in common_cols])).mappings().all()
            if not rows:
                print(f"· {tname}: 0 rows")
                continue

            stmt = pg_insert(dst_table)
            # ON CONFLICT DO NOTHING on the primary key keeps the load idempotent.
            pk_cols = [c.name for c in dst_table.primary_key.columns]
            stmt = stmt.on_conflict_do_nothing(index_elements=pk_cols) if pk_cols else stmt
            dconn.execute(stmt, [dict(r) for r in rows])
            print(f"✓ {tname}: {len(rows)} rows")

        # Realign identity sequences so new inserts don't collide with copied ids.
        for tname, idcol in IDENTITY_COLS.items():
            if tname in skip:
                continue
            if f"public.{tname}" not in dst_meta.tables:
                continue
            dconn.execute(text(
                f"SELECT setval(pg_get_serial_sequence('public.{tname}', :col), "
                f"COALESCE((SELECT MAX({idcol}) FROM public.{tname}), 1), true)"
            ), {"col": idcol})
            print(f"↻ sequence realigned: {tname}.{idcol}")

    print("\nDone. Remember: public.users.auth_id is NULL until linked to Supabase Auth.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
