-- Switch the shipping carrier from GHN (Giao Hàng Nhanh) to VTP (Viettel Post).
--
-- GHN is gone from the code entirely. What stays is the *data*: orders already
-- shipped through GHN keep their waybill and their address, so the admin panel
-- and the customer's order history still render. That is why every column here
-- is RENAMED rather than dropped and recreated — a rename keeps the values.
--
-- The renamed columns are carrier-neutral on purpose (`tracking_code`, not
-- `vtp_order_number`): the `carrier` column now says which carrier a row
-- belongs to, and the next switch is a value change, not another migration
-- like this one.

-- ---------------------------------------------------------------------------
-- orders: carrier-neutral shipping columns
-- ---------------------------------------------------------------------------
alter table public.orders rename column ghn_order_code       to tracking_code;
alter table public.orders rename column ghn_error            to shipping_error;
alter table public.orders rename column ghn_last_attempt_at  to shipping_last_attempt_at;
alter table public.orders rename column ghn_province_id      to ship_province_id;
alter table public.orders rename column ghn_district_id      to ship_district_id;
alter table public.orders rename column ghn_ward_code        to ship_ward_code;
alter table public.orders rename column ghn_province_name    to ship_province_name;
alter table public.orders rename column ghn_district_name    to ship_district_name;
alter table public.orders rename column ghn_ward_name        to ship_ward_name;

alter index if exists idx_orders_ghn_order_code rename to idx_orders_tracking_code;

comment on column public.orders.tracking_code is
  'Carrier waybill number. GHN order_code on historical rows, VTP ORDER_NUMBER on new ones — read it together with `carrier`.';
comment on column public.orders.shipping_error is
  'Why the carrier refused or never received this shipment. Null once a waybill exists.';
comment on column public.orders.ship_ward_code is
  'Carrier ward identifier, kept as text because GHN wards were alphanumeric codes and VTP wards are numeric ids. The VTP client parses it back to an integer.';

-- Which carrier a row's tracking_code / ship_* ids belong to. Everything that
-- exists right now went through GHN; everything new goes through VTP, so the
-- default is VTP and the backfill claims the past for GHN.
alter table public.orders
    add column if not exists carrier text not null default 'VTP';

update public.orders set carrier = 'GHN';

alter table public.orders
    add constraint orders_carrier_check check (carrier in ('GHN', 'VTP'));

comment on column public.orders.carrier is
  'Shipping carrier for this order: GHN for orders placed before the Viettel Post switch, VTP after.';

-- VTP picks a service by string code ('LCOD', 'VHT', 'STK', …) where GHN used a
-- numeric service_id. `shipping_service_id` is left alone holding the GHN ids of
-- historical orders; nothing writes it any more.
alter table public.orders
    add column if not exists shipping_service_code text;

comment on column public.orders.shipping_service_id is
  'Legacy GHN numeric service id. No longer written — new orders use shipping_service_code.';
comment on column public.orders.shipping_service_code is
  'VTP service code chosen at checkout (MA_DV_CHINH), e.g. LCOD / STK / VHT.';

-- Latest carrier status snapshot, pushed by the VTP webhook. `orders.status`
-- still holds the normalised English status the admin UI renders; these columns
-- keep the carrier's own view next to it so a disputed delivery can be checked
-- without calling the API.
alter table public.orders
    add column if not exists carrier_status_code int,
    add column if not exists carrier_status_name text,
    add column if not exists carrier_status_at   timestamptz,
    add column if not exists carrier_location    text,
    add column if not exists carrier_is_returning boolean not null default false;

comment on column public.orders.carrier_status_code is
  'Raw VTP ORDER_STATUS from the most recent webhook event (101, 200, 501, …).';

-- ---------------------------------------------------------------------------
-- shipping_events: one row per carrier status push
-- ---------------------------------------------------------------------------
-- The GHN integration had no record of what the carrier told us, so an order
-- that went wrong left nothing to read back (see commit ed48b56). VTP pushes a
-- webhook per status change, and the unique key below is what makes handling it
-- idempotent — VTP redelivers up to 5 times when it doesn't get a prompt 200.
create table public.shipping_events (
    event_id      bigint generated by default as identity primary key,
    order_id      int not null references public.orders(order_id) on delete cascade,
    tracking_code text,
    status_code   int not null,
    status_name   text,
    location      text,
    note          text,
    reason_code   text,
    is_returning  boolean not null default false,
    status_at     timestamptz not null,
    raw_payload   jsonb,
    created_at    timestamptz not null default now(),
    constraint shipping_events_unique_event unique (order_id, status_code, status_at)
);

create index idx_shipping_events_order_id on public.shipping_events(order_id);

comment on table public.shipping_events is
  'Carrier status pushes (VTP webhook). The (order_id, status_code, status_at) unique key makes redelivered webhooks a no-op.';

alter table public.shipping_events enable row level security;

-- Read-only for humans: an admin sees every shipment's history, a signed-in
-- customer sees their own order's. There is deliberately no guest policy — the
-- pattern that granted guests access by `auth.uid() is null` leaked other
-- people's orders once already (20260807120000_fix_guest_order_read_leak).
-- Nobody writes through PostgREST; only the webhook does, as service_role.
create policy "shipping events admin read" on public.shipping_events
    for select using (public.is_admin());

create policy "own shipping events read" on public.shipping_events
    for select using (
        exists (
            select 1 from public.orders o
            where o.order_id = shipping_events.order_id
              and o.user_id = public.app_user_id()
        )
    );

-- ---------------------------------------------------------------------------
-- integration_tokens: server-side credential cache
-- ---------------------------------------------------------------------------
-- GHN's token was static and lived in an env var. VTP issues one that expires,
-- so it has to be stored somewhere both stateless edge function isolates can
-- see. Service-role only: RLS is on with no policy, which denies anon and
-- authenticated outright while the functions' service_role key bypasses it.
create table public.integration_tokens (
    name       text primary key,
    token      text not null,
    expires_at timestamptz,
    updated_at timestamptz not null default now()
);

comment on table public.integration_tokens is
  'Cached third-party API tokens that expire (currently the VTP long-term token). Readable only by service_role.';

alter table public.integration_tokens enable row level security;
