-- =============================================================================
-- Bookstore initial schema — ported from FastAPI/SQLAlchemy models (MySQL) to
-- Supabase Postgres.
--
-- Source: bookstore-backend/app/models/models.py + models/zalo_tokens.py
--
-- Conversion notes:
--   * MySQL LONGTEXT / Text          -> text
--   * Integer autoincrement PK       -> int generated by default as identity
--     (BY DEFAULT, not ALWAYS, so existing MySQL ids can be inserted verbatim
--      during data import; sequences are realigned at the bottom of this file)
--   * DECIMAL(5,2)                    -> numeric(5,2)
--   * DateTime(timezone=True) now()   -> timestamptz default now()
--   * BigInteger (payos_order_code)   -> bigint
--   * users.is_active stays int (0/1) to preserve the app's existing semantics
--   * A nullable users.auth_id (uuid) bridges each row to Supabase auth.users.
-- RLS is enabled in the companion migration 20260601120100_rls_and_auth.sql.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Roles & users
-- ---------------------------------------------------------------------------
create table public.roles (
    role_id   int generated by default as identity primary key,
    role_name varchar(50) not null unique
);

create table public.users (
    user_id                  int generated by default as identity primary key,
    role_id                  int not null references public.roles(role_id),
    -- Bridge to Supabase Auth. Null for legacy/guest-converted rows until linked.
    auth_id                  uuid unique references auth.users(id) on delete set null,
    first_name               varchar(100) not null,
    last_name                varchar(100) not null,
    email                    varchar(255) not null unique,
    -- Kept for historical import only; Supabase Auth owns credentials going forward.
    password_hash            varchar(255),
    created_at               timestamptz default now(),
    is_active                int default 0,            -- 0 = inactive until email verified
    reset_token              varchar(255),
    email_verification_token varchar(255),
    google_id                varchar(255) unique,
    profile_picture          varchar(500),
    auth_provider            varchar(50) not null default 'local',
    phone_number             varchar(20)
);
create index idx_users_email on public.users(email);
create index idx_users_google_id on public.users(google_id);
create index idx_users_auth_id on public.users(auth_id);

create table public.addresses (
    address_id          int generated by default as identity primary key,
    user_id             int not null references public.users(user_id) on delete cascade,
    phone_number        varchar(20) not null,
    address_line1       varchar(255) not null,
    address_line2       varchar(255),
    city                varchar(100) not null,
    postal_code         varchar(20) not null,
    country             varchar(100) not null,
    is_default_shipping boolean default false
);
create index idx_addresses_user_id on public.addresses(user_id);

-- ---------------------------------------------------------------------------
-- Catalog: authors, categories, books, stationery
-- ---------------------------------------------------------------------------
create table public.authors (
    author_id int generated by default as identity primary key,
    name      varchar(255) not null,
    bio       text
);

create table public.categories (
    category_id int generated by default as identity primary key,
    name        varchar(100) not null unique,
    description text
);

create table public.books (
    book_id             int generated by default as identity primary key,
    title               varchar(255) not null,
    slug                varchar(255) unique,
    isbn                varchar(13) unique,
    brief_description   text,
    full_description    text,
    price               int not null,
    stock_quantity      int not null default 0,
    publication_date    date,
    image_url           varchar(500),
    image2_url          varchar(500),
    image3_url          varchar(500),
    read_sample         text,                 -- JSON array of image paths
    audio_sample        varchar(500),
    is_active           boolean not null default true,
    created_at          timestamptz default now(),
    publisher           varchar(255),
    pages               int,
    height              numeric(5,2),
    width               numeric(5,2),
    length              numeric(5,2),
    weight              int,                  -- grams
    is_discount         boolean not null default false,
    is_slide1           boolean not null default false,
    is_slide2           boolean not null default false,
    is_slide3           boolean not null default false,
    is_free_ship        boolean not null default false,
    is_featured         boolean not null default false,
    display_order       int not null default 0,
    discount_percentage numeric(5,2),
    discount_amount     int,
    discounted_price    int
);
create index idx_books_slug on public.books(slug);

create table public.stationery (
    stationery_id       int generated by default as identity primary key,
    title               varchar(255) not null,
    slug                varchar(255) unique,
    sku                 varchar(50) unique,
    brief_description   text,
    full_description    text,
    price               int not null,
    stock_quantity      int not null default 0,
    image_url           varchar(500),
    image2_url          varchar(500),
    image3_url          varchar(500),
    is_active           boolean not null default true,
    created_at          timestamptz default now(),
    height              numeric(5,2),
    width               numeric(5,2),
    length              numeric(5,2),
    weight              int,                  -- grams
    is_discount         boolean not null default false,
    is_slide1           boolean not null default false,
    is_slide2           boolean not null default false,
    is_slide3           boolean not null default false,
    is_free_ship        boolean not null default false,
    is_featured         boolean not null default false,
    display_order       int not null default 0,
    discount_percentage numeric(5,2),
    discount_amount     int,
    discounted_price    int
);
create index idx_stationery_slug on public.stationery(slug);

-- Many-to-many junctions
create table public.book_authors (
    book_id   int not null references public.books(book_id) on delete cascade,
    author_id int not null references public.authors(author_id) on delete cascade,
    primary key (book_id, author_id)
);

create table public.book_categories (
    book_id     int not null references public.books(book_id) on delete cascade,
    category_id int not null references public.categories(category_id) on delete cascade,
    primary key (book_id, category_id)
);

create table public.stationery_categories (
    stationery_id int not null references public.stationery(stationery_id) on delete cascade,
    category_id   int not null references public.categories(category_id) on delete cascade,
    primary key (stationery_id, category_id)
);

-- ---------------------------------------------------------------------------
-- Reviews & wishlist
-- ---------------------------------------------------------------------------
create table public.reviews (
    review_id  int generated by default as identity primary key,
    book_id    int not null references public.books(book_id) on delete cascade,
    user_id    int not null references public.users(user_id) on delete cascade,
    rating     int not null check (rating between 1 and 5),
    comment    text,
    created_at timestamptz default now()
);
create index idx_reviews_book_id on public.reviews(book_id);
create index idx_reviews_user_id on public.reviews(user_id);

create table public.stationery_reviews (
    review_id     int generated by default as identity primary key,
    stationery_id int not null references public.stationery(stationery_id) on delete cascade,
    user_id       int not null references public.users(user_id) on delete cascade,
    rating        int not null check (rating between 1 and 5),
    comment       text,
    created_at    timestamptz default now()
);
create index idx_stationery_reviews_stationery_id on public.stationery_reviews(stationery_id);
create index idx_stationery_reviews_user_id on public.stationery_reviews(user_id);

create table public.wishlists (
    user_id  int not null references public.users(user_id) on delete cascade,
    book_id  int not null references public.books(book_id) on delete cascade,
    added_at timestamptz default now(),
    primary key (user_id, book_id)
);

-- ---------------------------------------------------------------------------
-- Orders & order items
-- ---------------------------------------------------------------------------
create table public.orders (
    order_id               int generated by default as identity primary key,
    user_id                int references public.users(user_id) on delete set null,  -- nullable for guest orders
    order_date             timestamptz default now(),
    total_amount           int not null,
    status                 varchar(50) not null default 'Pending',
    -- Guest checkout fields (null when placed by a registered user)
    guest_email            varchar(255),
    shipping_phone_number  varchar(20),
    shipping_address_line1 varchar(255),
    shipping_address_line2 varchar(255),
    shipping_city          varchar(100),
    shipping_postal_code   varchar(20),
    shipping_country       varchar(100),
    -- Shipping / payment
    shipping_method        varchar(100),
    payment_method         varchar(100),
    cod_amount             int,
    payment_status         varchar(20) not null default 'Unpaid',
    paid_at                timestamptz,
    -- PayOS
    payos_order_code       bigint,
    payos_payment_link_id  varchar(64),
    payos_checkout_url     varchar(512),
    shipping_full_name     varchar(255),
    -- GHN
    ghn_order_code         varchar(50),
    ghn_province_id        int,
    ghn_district_id        int,
    ghn_ward_code          varchar(20),
    ghn_province_name      varchar(100),
    ghn_district_name      varchar(100),
    ghn_ward_name          varchar(100),
    shipping_service_id    int,
    shipping_fee           int,
    package_weight         int,
    package_length         int,
    package_width          int,
    package_height         int
);
create index idx_orders_user_id on public.orders(user_id);
create index idx_orders_payos_order_code on public.orders(payos_order_code);
create index idx_orders_ghn_order_code on public.orders(ghn_order_code);

create table public.order_items (
    order_item_id     int generated by default as identity primary key,
    order_id          int not null references public.orders(order_id) on delete cascade,
    book_id           int references public.books(book_id) on delete set null,
    stationery_id     int references public.stationery(stationery_id) on delete set null,
    quantity          int not null,
    price_at_purchase int not null
);
create index idx_order_items_order_id on public.order_items(order_id);

-- ---------------------------------------------------------------------------
-- CMS: slides, notifications, admin codes
-- ---------------------------------------------------------------------------
create table public.slide_contents (
    slide_content_id          int generated by default as identity primary key,
    slide_number              int not null,
    title                     varchar(255),
    body                      text,
    title_color               varchar(20),
    body_color                varchar(20),
    primary_button_bg_color   varchar(20),
    primary_button_text_color varchar(20),
    secondary_button_bg_color varchar(20),
    secondary_button_text_color varchar(20),
    primary_button_label      varchar(255),
    secondary_button_label    varchar(255),
    primary_button_url        varchar(500),
    secondary_button_url      varchar(500),
    selected_item_type        varchar(20),   -- 'book' | 'stationery'
    selected_item_id          int,
    title_font_size           varchar(10),
    body_font_size            varchar(10),
    title_font_family         varchar(50),
    body_font_family          varchar(50),
    image_width               varchar(10),
    image_height              varchar(10),
    created_at                timestamptz default now(),
    updated_at                timestamptz default now()
);
create index idx_slide_contents_slide_number on public.slide_contents(slide_number);

create table public.notifications (
    notification_id  int generated by default as identity primary key,
    message          varchar(500),
    is_active        boolean not null default true,
    background_color varchar(20) default '#008080',
    text_color       varchar(20) default '#FFFFFF',
    text_align       varchar(10) default 'center',
    font_weight      varchar(10) default 'normal',
    image_url        text,
    mobile_image_url text,
    created_at       timestamptz default now(),
    updated_at       timestamptz default now()
);
create index idx_notifications_is_active on public.notifications(is_active);

create table public.admin_login_codes (
    id         int generated by default as identity primary key,
    code       varchar(6) not null unique,
    created_at timestamptz default now(),
    expires_at timestamptz not null,
    is_active  boolean not null default true
);
create index idx_admin_login_codes_code on public.admin_login_codes(code);

-- Note: the old `zalo_tokens` table is intentionally dropped — Zalo ZNS has
-- been retired in favour of email order notifications (see supabase/MIGRATION.md).

-- ---------------------------------------------------------------------------
-- updated_at maintenance (replaces SQLAlchemy onupdate=func.now())
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger trg_slide_contents_updated_at
    before update on public.slide_contents
    for each row execute function public.set_updated_at();

create trigger trg_notifications_updated_at
    before update on public.notifications
    for each row execute function public.set_updated_at();
